default[:dukesbankDeveloper][:workspace] =  "/home/dukesbank/workspace"
default[:dukesbankDeveloper][:hudsonProjectXml] = "/home/dukesbank/hudson-project.xml"
default[:dukesbankDeveloper][:jobsTemplateDir] = "rundeck/var/rundeck/projects/dukesbank/jobs.d"
default[:dukesbankDeveloper][:jobs] = "code-promote"
default[:dukesbankDeveloper][:user] = "dukesbank"
default[:dukesbankDeveloper][:group] = "dukesbank"
